org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.07

minecraft_version=1.21
minecraft_version_range=[1.21,1.22)
neo_version=21.0.78-beta
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

mod_id=luckytntlib
mod_group_id=luckytntlib
mod_name=Lucky TNT Lib
mod_license=All Rights Reserved
mod_version=21.0.78.2
mod_authors=SlimingHD, Fleshcrafter
mod_description=This mod acts as a library for TNT mods usually associated with the word "Lucky". \n It allows for quick creation and easy maintenance of TNT mods and is a hard dependency.